// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChlpH7AH3d3fTHrw_KReK4JqHkNLmTYRY',
    appId: '1:748591270569:web:aaafbc3f582121048777b8',
    messagingSenderId: '748591270569',
    projectId: 'healthy-b7635',
    authDomain: 'healthy-b7635.firebaseapp.com',
    storageBucket: 'healthy-b7635.appspot.com',
    measurementId: 'G-N4QN7BP121',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWOz8aN0NhN2Na__DuVGeVpJyQhGMYDjk',
    appId: '1:748591270569:android:8e76e76689f345f38777b8',
    messagingSenderId: '748591270569',
    projectId: 'healthy-b7635',
    storageBucket: 'healthy-b7635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLhFl1zEkgmaf771OLJ1kLVefl05uLcW4',
    appId: '1:748591270569:ios:1107c7305ef281b88777b8',
    messagingSenderId: '748591270569',
    projectId: 'healthy-b7635',
    storageBucket: 'healthy-b7635.appspot.com',
    iosClientId: '748591270569-g1379pdgaj5ikqkq0cgkpsa08uf8ontp.apps.googleusercontent.com',
    iosBundleId: 'fr.benoitfontaine.healthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLhFl1zEkgmaf771OLJ1kLVefl05uLcW4',
    appId: '1:748591270569:ios:1107c7305ef281b88777b8',
    messagingSenderId: '748591270569',
    projectId: 'healthy-b7635',
    storageBucket: 'healthy-b7635.appspot.com',
    iosClientId: '748591270569-g1379pdgaj5ikqkq0cgkpsa08uf8ontp.apps.googleusercontent.com',
    iosBundleId: 'fr.benoitfontaine.healthy',
  );
}
